# Generated by Django 3.2.9 on 2022-04-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudApp', '0003_auto_20220430_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
