# Generated by Django 3.2.9 on 2022-04-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudApp', '0004_file_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Uploaded_By',
            field=models.CharField(blank=True, default=None, max_length=90, null=True),
        ),
    ]
