# Generated by Django 3.2.9 on 2022-05-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudApp', '0005_alter_file_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Size',
            field=models.CharField(blank=True, default=None, max_length=90, null=True),
        ),
    ]
