# Generated by Django 3.2.9 on 2022-05-01 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CloudApp', '0006_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='Size',
        ),
    ]
