# Generated by Django 3.2.9 on 2022-05-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudApp', '0007_remove_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='File_Size',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
