# Generated by Django 3.2.9 on 2022-05-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudApp', '0008_file_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='File_Name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
